### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by timhughes** [r-kells/scream#47]
Getting the following when trying the example in the readme.
```
$ python --version
Python 3.8.2
 $ pip freeze
appdirs==1.4.3
coverage==5.1
distlib==0.3.0
filelock==3.0.12
flake8==3.6.0
flake8-polyfill==1.0.2
importlib-metadata==0.23
mccabe==0.6.1
packaging==20.3
pep8-naming==0.7.0
pluggy==0.13.1
py==1.8.1
pycodestyle==2.4.0
pyflakes==2.0.0
pyparsing==2.4.7
scream==0.0.34
six==1.14.0
toml==0.10.0
tox==3.13.2
virtualenv==20.0.20
zipp==3.1.0
```

```
thughes@krypton [0] $ scream init
Initialized empty Git repository in /home/thughes/git/python_messagequeue_app/.git/
Done!
Create a new package with `scream new <namespace>.<package_name>`
Fri May 08 22:34:18 [ ~/git/python_messagequeue_app (master #%) ] go:1.14.2 py:3.8.2 rb:system 
thughes@krypton [0] $ scream new com.packagea
Created project `com.packagea`
Fri May 08 22:34:32 [ ~/git/python_messagequeue_app (master #%) ] go:1.14.2 py:3.8.2 rb:system 
thughes@krypton [0] $ scream new com.packageb
Created project `com.packageb`
Fri May 08 22:34:35 [ ~/git/python_messagequeue_app (master #%) ] go:1.14.2 py:3.8.2 rb:system 
thughes@krypton [0] $ scream test --all --parallel
Testing all packages...
Traceback (most recent call last):
  File "/home/thughes/.pyenv/versions/3.8.2/bin/tox", line 10, in <module>
    sys.exit(cmdline())
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 64, in main
    config = load_config(args)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/session/__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 254, in parseconfig
    pm = get_plugin_manager(plugins)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/tox/config/__init__.py", line 73, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pluggy/manager.py", line 289, in load_setuptools_entrypoints
    for dist in importlib_metadata.distributions():
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/importlib/metadata.py", line 194, in <genexpr>
    resolver(context)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 417, in find_distributions
    found = self._search_paths(context.pattern, context.path)
AttributeError: 'Context' object has no attribute 'pattern'
Traceback (most recent call last):
  File "/home/thughes/.pyenv/versions/3.8.2/bin/scream", line 10, in <module>
    sys.exit(Scream())
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scream/cli/main.py", line 75, in __init__
    getattr(self, args.command)()
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scream/cli/main.py", line 133, in test
    test(all_packages=self.monorepo.config.packages, package_name=args.package_name, dry_run=args.dry_run,
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scream/commands/test.py", line 22, in test
    result = subprocess.check_call(cmd)
  File "/home/thughes/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tox', '-p', 'all']' returned non-zero exit status 1.
```

**Comment by r-kells** [comment]
Sorry, I haven't been too active here. Thanks for the issue. Looks like this library is not yet compatible with python 3.8.

Let me know if you are still interested in using this and I'd be happy to put some time in to upgrade.

**Comment by timhughes** [comment]
Don't do anything on my behalf. I was just trying a bunch of different tools. I raised a ticket because I prefer feedback on my projects when people have problems rather than not knowing there was a problem. Doesn't mean I will have any time to fix them :-)
