### ISSUE TITLE
Invalid specifier in setup.cfg

### ISSUE THREAD

**Issue by timhughes** [r-kells/scream#49]
Tried running on 3.7 got the following issue. I tracked to down to the generated  `setup.cfg` having `python_requires = 3.7` rather than `python_requires = >=3.7` or something similar https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires  

```
thughes@krypton [0] $ scream test --all --parallel
Testing all packages...
⠼ [2] py37-org_timhughes_rabbit | py37-org_timhughes_rabbit-uiERROR: invocation failed (exit code 1), logfile: /home/thughes/tmp/scream_test/.tox/py37-org_timhughes_rabbit-ui/log/py37-org_timhughes_rabbit-ui-4.log
================================================================================================================= log start ==================================================================================================================
py37-org_timhughes_rabbit-ui installed: appdirs==1.4.4,coverage==5.2,distlib==0.3.1,filelock==3.0.12,flake8==3.6.0,flake8-polyfill==1.0.2,importlib-metadata==0.23,mccabe==0.6.1,packaging==20.4,pep8-naming==0.7.0,pluggy==0.13.1,py==1.9.0,pycodestyle==2.4.0,pyflakes==2.0.0,pyparsing==2.4.7,scream==0.0.34,six==1.15.0,toml==0.10.1,tox==3.13.2,virtualenv==20.0.25,zipp==3.1.0
py37-org_timhughes_rabbit-ui run-test-pre: PYTHONHASHSEED='1513154788'
py37-org_timhughes_rabbit-ui run-test: commands[0] | flake8 rabbit --config=/home/thughes/tmp/scream_test/tox.ini --statistics
py37-org_timhughes_rabbit-ui run-test: commands[1] | scream install org_timhughes_rabbit --test
Installing package: `org_timhughes_rabbit`...
ERROR: Processing ./rabbit
    ERROR: Command errored out with exit status 1:
     command: /home/thughes/tmp/scream_test/.tox/py37-org_timhughes_rabbit-ui/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_4mpbadq/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_4mpbadq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9hd2zpok
         cwd: /tmp/pip-req-build-_4mpbadq/
    Complete output (34 lines):
    Traceback (most recent call last):
      File "/home/thughes/tmp/scream_test/.tox/py37-org_timhughes_rabbit-ui/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 579, in __init__
        parsed.add(Specifier(specifier))
      File "/home/thughes/tmp/scream_test/.tox/py37-org_timhughes_rabbit-ui/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 84, in __init__
        raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
    setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '3.7'
```

**Comment by r-kells** [comment]
Probably should have pinned my setuptools version. The logic for parsing `python_requires` is also pretty crude to begin with and needs some love.
